### ISSUE TITLE
Create Ability to Write to Log File

### ISSUE THREAD

**Issue by GodfreyL3** [Ctr011/Resolv-LLC#6]
Application must be able to write to a log.txt file on the local system (.txt/.log). Must take in 
- Date (Month DD YYYY HH:mm): Windows API
- Comment: Argument from user

**Comment by Ctr011** [comment]
For the system, Im thinking of having it update every minute, though will get back to this soon. Going to recheck the example log files within the slides.

**Comment by Ctr011** [comment]
currently have the log files being created, this next part is setting the system for the individuals to log files

**Comment by Ctr011** [comment]
Current system allows for user input to log file, backups to log file, and creation of hidden directories. 

For backups, we need to create need to create some sort of system loop (server call) that will continuously call the getTime function to see if the interval 30 minute interval has occurred...Backups occur when the hour changes and half-past the hour.  

directories are no problem now as they will be located in the following:
 C:\Users\%USERPROFILE%\AppData\Roaming\ResolvDeckware\         (for Original Log File)
 C:\Users\%USERPROFILE%\AppData\Roaming\ResolvBack\                  (for Backup Log File)
 ---> both have hidden attributes, unless user running on view all (including hidden files)
 
 Currently need to work on the writing system for the log file, need to add some sort of error code for incorrect inputs...Currently have code that can write to file.
 
 Another item that I need to create is the following: Switch case for the different systems that will be inputted within the system.
 
 Test cases are found within the main() function...

**Comment by Ctr011** [comment]
Pretty much done with the logging function. all there is to finish the UI and update server to be able to further test it out

**Comment by Ctr011** [comment]
UI now works with Logging Function... Closing issue
